### ISSUE TITLE
ConsoleTable: Chinese characters support

### ISSUE THREAD

**Issue by ziang-info** [clyoudu/clyoudu-util#2]
ConsoleTable is a nice tools for console table printing.

But it can't support Chinese characters well.

If there are some Chinese characters in the header or row cells, the table columns will not stay in line.

**Comment by clyoudu** [comment]
This may be due to your console font is not monospaced(等宽字体), or the monospace font not support Chinese. 

Another similar issue #1 

Let's see this(with IntelliJ IDEA):
First, print a table contains Chinese.
![image](https://user-images.githubusercontent.com/9692275/93971498-e531d900-fda2-11ea-97fa-c40583c5658f.png)
Oops, let's change the console font.
![image](https://user-images.githubusercontent.com/9692275/93971867-bd8f4080-fda3-11ea-8619-ed8ed084b78d.png)
In most situation, it doesn't work for Chinese. Because most of those 'monospaced' fonts doesn't support Chinese, and these 'monospaced' fonts display one Chinese character as wide as 1.x(nether 1 nor 2) English characters(or space).

Why Chinese character cannot displayed as wide as English Character? Because CJK character (Chinese, Japanese, Korean) is more complex than English. You'd better google it, i cant explain it clearly.

So, we may have to change the console fonts to some monospaced fonts which supports Chinese, make sure one Chinese character displayed as wide as 2 English character. You can see our commits to make Chinese character returns 2 when called length method in issue #1 

If you want install a monospaced font support Chinese, this website maybe helpful: [中文等宽字体（Monospace Chinese Font Family）](https://leonvision.online/technology/monospace-chinese-font-family/). And most Windows system default Chinese font is monospaced, such as Song(宋体), Hei(黑体), Kai(楷体). But unfortunately, PingFang SC/HK/TC(苹方), which is system default Chinese font on MacOS, is not monospaced.

I use 'Noto Sans Mono CJK SC' which display well: [Noto CJK](https://www.google.com/get/noto/help/cjk/)


 chinese font(中文等宽字体)

**Comment by ziang-info** [comment]
> ospaced(等宽字体), or the monospace font not support Chinese.
> 
> Another similar issue #1

Got it.
Thanks!
